# Generated by Django 5.1.2 on 2024-11-06 01:57

from django.db import migrations

def populate_priorities(apps, schemaeditor):
    Priority = apps.get_model('issues', 'Priority')
    priorities = {
        'low': 'A low priority issue',
        'medium': 'Issue of medium priority',
        'high': 'A high priority issue'
    }
    for key, value in priorities.items():
        priority = Priority(name=key, description=value)
        priority.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_priorities)
    ]
