# Generated by Django 5.1.2 on 2024-11-02 17:35

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "alpha" : "the A team",
        "bravo" : "the B team",
        "charlie" : "the C team"
    }
    Teams = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team = Teams(name=key, description=value)
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241102_1035'),
    ]

    operations = [
        migrations.RunPython(populate_team)
    ]
